from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.colors import black, red



def generate_report_pdf(buffer, report_json):
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    y = height - 40

    # SECTION 1 — HEADER
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, y, report_json["organization"]["name"])

    c.setFont("Helvetica", 9)
    y -= 14
    c.drawString(40, y, report_json["organization"]["address"] or "")

    c.setFont("Helvetica-Bold", 14)
    c.drawRightString(width - 40, height - 40, "Psychiatric Assessment Report")

    y -= 30
    c.setFont("Helvetica", 9)
    c.drawString(40, y, f"Report ID: {report_json['report_id']}")
    y -= 12
    c.drawString(40, y, f"Report Date: {report_json['audit']['created_at']}")

    # SECTION 2 — PATIENT & ENCOUNTER
    y -= 30
    c.setFont("Helvetica-Bold", 11)
    c.drawString(40, y, "Patient & Encounter Details")

    y -= 16
    c.setFont("Helvetica", 9)
    p = report_json["patient"]
    e = report_json["encounter"]

    c.drawString(40, y, f"Patient Name: {p['name']}")
    y -= 12
    c.drawString(40, y, f"Gender: {p['gender']}")
    y -= 12
    c.drawString(40, y, f"Encounter Type: {e['type']}")
    y -= 12
    c.drawString(40, y, f"Assessment Date: {e['date_time']}")

    # SECTION 3 — ASSESSMENT SUMMARY
    y -= 30
    c.setFont("Helvetica-Bold", 11)
    c.drawString(40, y, "Assessment Summary")

    y -= 16
    c.setFont("Helvetica", 9)

    for t in report_json["tests"]:
        if t["red_flags"]:
            c.setFillColor(red)
        c.drawString(40, y, f"{t['test_code']} — Score: {t['score']} — {t['severity']}")
        c.setFillColor(black)
        y -= 12

    # SECTION 5 — SAFETY FLAGS
    if report_json["system_notes"]["red_flag_present"]:
        y -= 20
        c.setFont("Helvetica-Bold", 11)
        c.setFillColor(red)
        c.drawString(40, y, "Important Safety Information")
        c.setFillColor(black)

        y -= 14
        c.setFont("Helvetica", 9)
        c.drawString(40, y, "Immediate clinical evaluation is required.")
        y -= 12
        c.drawString(40, y, "Tele-MANAS Mental Health Helpline: 14416")

    # SECTION 8 — LEGAL DISCLAIMER
    y -= 30
    c.setFont("Helvetica", 8)
    c.drawString(
        40,
        y,
        "This report is generated by a software-based psychiatric assessment system and does not constitute a medical diagnosis."
    )

    # FOOTER
    c.setFont("Helvetica", 8)
    c.drawRightString(
        width - 40,
        20,
        f"Generated by NeurovaX Clinical Engine | Page 1"
    )

    c.showPage()
    c.save()
