# Generated by Django 5.2.4 on 2025-12-31 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('org_type', models.CharField(choices=[('HOSPITAL', 'HOSPITAL'), ('DIAGNOSTIC', 'DIAGNOSTIC')], max_length=20)),
                ('signature_required', models.BooleanField(default=False)),
                ('default_release_policy', models.CharField(choices=[('CLINICIAN_ONLY', 'CLINICIAN_ONLY'), ('PATIENT_AND_CLINICIAN', 'PATIENT_AND_CLINICIAN')], default='CLINICIAN_ONLY', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ORG_ADMIN', 'ORG_ADMIN'), ('CLINICIAN', 'CLINICIAN'), ('STAFF', 'STAFF'), ('AUDITOR', 'AUDITOR')], max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
