# Generated by Django 5.2.4 on 2026-01-12 06:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='external_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='External clinical organization UUID', unique=True),
        ),
    ]
