# Generated by Django 5.2.4 on 2025-12-31 15:06

import common.immutability
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_sessions', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_json', models.JSONField()),
                ('pdf_file', models.FileField(upload_to='reports/')),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('READY', 'READY'), ('RELEASED', 'RELEASED')], default='READY', max_length=20)),
                ('release_policy', models.CharField(choices=[('CLINICIAN_ONLY', 'CLINICIAN_ONLY'), ('PATIENT_AND_CLINICIAN', 'PATIENT_AND_CLINICIAN')], default='CLINICIAN_ONLY', max_length=30)),
                ('report_schema_version', models.CharField(max_length=20)),
                ('engine_version', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='clinical_sessions.session')),
            ],
            bases=(common.immutability.ImmutableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReportSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=255)),
                ('signer_reg_no', models.CharField(max_length=100)),
                ('signer_role', models.CharField(max_length=100)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('signature_meta', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
            bases=(common.immutability.ImmutableModelMixin, models.Model),
        ),
    ]
