# Generated by Django 5.2.4 on 2026-01-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_sessions', '0004_consentrecord_clinical_se_organiz_411bc4_idx_and_more'),
        ('core', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['organization', 'status'], name='reports_rep_organiz_ae5072_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['organization', 'created_at'], name='reports_rep_organiz_b5f8b2_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsignature',
            index=models.Index(fields=['organization', 'signed_at'], name='reports_rep_organiz_82b560_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsignature',
            index=models.Index(fields=['organization', 'report'], name='reports_rep_organiz_13caca_idx'),
        ),
    ]
