# Generated by Django 5.2.4 on 2026-01-03 05:06

import reports.storage_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_reports_rep_organiz_ae5072_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(upload_to=reports.storage_paths.report_upload_path),
        ),
    ]
