# Generated by Django 5.2.4 on 2026-01-10 06:06

import reports.storage_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=reports.storage_paths.report_upload_path),
        ),
    ]
