# Generated by Django 5.2.4 on 2026-01-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_delete_clinicalreport'),
        ('reports', '0005_alter_report_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.CharField(max_length=10)),
                ('engine_version', models.CharField(max_length=10)),
                ('report_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_frozen', models.BooleanField(default=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinicalreport', to='clinical.clinicalorder')),
            ],
            options={
                'db_table': 'reports_clinicalreport',
            },
        ),
    ]
