# Generated by Django 5.2.4 on 2026-01-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_clinicalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalreport',
            name='status',
            field=models.CharField(choices=[('GENERATED', 'Generated'), ('SIGNED', 'Signed')], default='GENERATED', max_length=20),
        ),
    ]
