# Generated by Django 5.2.4 on 2026-01-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_clinicalreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalreport',
            name='review_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEWED', 'Reviewed')], db_index=True, default='DRAFT', max_length=16),
        ),
        migrations.AddField(
            model_name='clinicalreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalreport',
            name='reviewed_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicalreport',
            name='reviewed_by_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicalreport',
            name='reviewed_by_user_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='clinicalreport',
            name='validation_status',
            field=models.CharField(choices=[('VALIDATION_PENDING', 'Validation pending'), ('DATA_VALIDATED', 'Data validated'), ('VALIDATION_FAILED', 'Validation failed')], db_index=True, default='VALIDATION_PENDING', max_length=32),
        ),
    ]
