# Generated by Django 5.2.4 on 2026-01-24 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_clinicalreport_review_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalreport',
            name='correction_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clinicalreport',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='clinicalreport',
            name='supersedes_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='reports.clinicalreport'),
        ),
    ]
