# Generated by Django 5.2.4 on 2026-01-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_clinicalorder_phone_number'),
        ('reports', '0009_clinicalreport_correction_reason_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clinicalreport',
            constraint=models.UniqueConstraint(fields=('order',), name='one_report_per_order'),
        ),
        migrations.AlterModelTable(
            name='clinicalreport',
            table=None,
        ),
    ]
