# Generated by Django 5.2.4 on 2026-01-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_clinicalreport_one_report_per_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalreport',
            name='pdf_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
