# Generated by Django 5.2.4 on 2026-01-02 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_sessions', '0002_sessionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_given', models.BooleanField()),
                ('source', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='clinical_sessions.session')),
            ],
        ),
    ]
