# Generated by Django 5.2.4 on 2026-01-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('clinical_sessions', '0003_sessionconsent'),
        ('core', '0001_initial'),
        ('orders', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['organization', 'patient'], name='clinical_se_organiz_411bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['organization', 'created_at'], name='clinical_se_organiz_8fc565_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['organization', 'session'], name='clinical_se_organiz_edec76_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['organization', 'test'], name='clinical_se_organiz_397287_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['organization', 'status'], name='clinical_se_organiz_0d95a8_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['organization', 'created_at'], name='clinical_se_organiz_eacaed_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['organization', 'order'], name='clinical_se_organiz_d08c99_idx'),
        ),
    ]
