# Generated by Django 5.2.4 on 2026-01-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_sessions', '0004_consentrecord_clinical_se_organiz_411bc4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrecord',
            name='capture_mode',
            field=models.CharField(default='KIOSK', max_length=20),
        ),
    ]
