# Generated by Django 5.2.4 on 2026-01-31 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_sessions', '0005_alter_consentrecord_capture_mode'),
        ('core', '0003_organization_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_session_consents', to='core.organization'),
        ),
    ]
