# Generated by Django 5.2.4 on 2026-01-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgclinicalpolicy',
            name='token_validity_hours',
            field=models.IntegerField(default=48),
        ),
    ]
