import io
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm

def _draw_kv(c, x, y, k, v, k_w=45*mm):
    c.setFont("Helvetica-Bold", 9)
    c.drawString(x, y, str(k))
    c.setFont("Helvetica", 9)
    c.drawString(x + k_w, y, str(v) if v is not None else "-")

def generate_report_pdf_bytes(report_context: dict) -> bytes:
    """
    report_context expected keys:
      header: {...}
      patient: {...}
      order: {...}
      summary: {...}
      tests: list of {...}
      red_flags: list[str]
      disclaimers: list[str]
      signoff: {...}
    """
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4

    # margins
    left = 18 * mm
    right = width - 18 * mm
    top = height - 18 * mm
    y = top

    # Header
    c.setFont("Helvetica-Bold", 14)
    c.drawString(left, y, report_context["header"].get("title", "Psychiatric Assessment Report"))
    y -= 8 * mm

    c.setFont("Helvetica", 9)
    c.drawString(left, y, report_context["header"].get("subtitle", "Standardized Assessment Summary (Non-Diagnostic)"))
    y -= 10 * mm

    # Patient + Order block (2 columns)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(left, y, "Patient Information")
    y -= 6 * mm

    patient = report_context.get("patient", {})
    order = report_context.get("order", {})

    _draw_kv(c, left, y, "Name", patient.get("full_name"))
    _draw_kv(c, left + 90*mm, y, "Age / Sex", f'{patient.get("age","-")} / {patient.get("sex","-")}')
    y -= 5 * mm
    _draw_kv(c, left, y, "MRN/UHID", patient.get("mrn"))
    _draw_kv(c, left + 90*mm, y, "Phone", patient.get("phone"))
    y -= 8 * mm

    c.setFont("Helvetica-Bold", 11)
    c.drawString(left, y, "Assessment Details")
    y -= 6 * mm
    _draw_kv(c, left, y, "Battery", order.get("battery_code"))
    _draw_kv(c, left + 90*mm, y, "Version", order.get("battery_version"))
    y -= 5 * mm
    _draw_kv(c, left, y, "Administration", order.get("administration_mode"))
    _draw_kv(c, left + 90*mm, y, "Encounter", order.get("encounter_type"))
    y -= 5 * mm
    _draw_kv(c, left, y, "Created At", order.get("created_at"))
    _draw_kv(c, left + 90*mm, y, "Completed At", order.get("completed_at"))
    y -= 10 * mm

    # Summary
    summary = report_context.get("summary", {})
    c.setFont("Helvetica-Bold", 11)
    c.drawString(left, y, "Summary")
    y -= 6 * mm
    _draw_kv(c, left, y, "Primary Severity", summary.get("primary_severity"))
    _draw_kv(c, left + 90*mm, y, "Red Flags", "YES" if summary.get("has_red_flags") else "NO")
    y -= 8 * mm

    # Red flags section
    red_flags = report_context.get("red_flags", [])
    if red_flags:
        c.setFont("Helvetica-Bold", 11)
        c.drawString(left, y, "Critical Flags (Clinician Attention)")
        y -= 6 * mm
        c.setFont("Helvetica", 9)
        for rf in red_flags[:10]:
            c.drawString(left + 4*mm, y, f"• {rf}")
            y -= 4.5 * mm
        y -= 4 * mm

    # Tests table header
    c.setFont("Helvetica-Bold", 11)
    c.drawString(left, y, "Test Results")
    y -= 6 * mm

    # table columns
    col1 = left
    col2 = left + 70*mm
    col3 = left + 120*mm

    c.setFont("Helvetica-Bold", 9)
    c.drawString(col1, y, "Instrument")
    c.drawString(col2, y, "Score")
    c.drawString(col3, y, "Band / Notes")
    y -= 4 * mm
    c.line(left, y, right, y)
    y -= 5 * mm

    c.setFont("Helvetica", 9)
    tests = report_context.get("tests", [])
    for t in tests:
        if y < 55 * mm:
            c.showPage()
            y = top

        c.drawString(col1, y, str(t.get("name", "-"))[:35])
        c.drawString(col2, y, str(t.get("score", "-"))[:12])
        c.drawString(col3, y, str(t.get("band", "-"))[:40])
        y -= 5 * mm

    y -= 6 * mm

    # Disclaimers
    disclaimers = report_context.get("disclaimers", [])
    if y < 60 * mm:
        c.showPage()
        y = top
    c.setFont("Helvetica-Bold", 10)
    c.drawString(left, y, "Disclaimer")
    y -= 5 * mm
    c.setFont("Helvetica", 8.5)
    for d in disclaimers[:8]:
        c.drawString(left + 2*mm, y, f"• {d}")
        y -= 4.2 * mm

    y -= 6 * mm

    # Signature block
    signoff = report_context.get("signoff", {})
    c.setFont("Helvetica-Bold", 10)
    c.drawString(left, y, "Clinical Sign-off")
    y -= 6 * mm
    _draw_kv(c, left, y, "Status", signoff.get("status", "PENDING"))
    _draw_kv(c, left + 90*mm, y, "Signed At", signoff.get("signed_at", "-"))
    y -= 5 * mm
    _draw_kv(c, left, y, "Signed By", signoff.get("signed_by", "-"))
    _draw_kv(c, left + 90*mm, y, "Role", signoff.get("role", "-"))
    y -= 10 * mm

    # footer
    c.setFont("Helvetica", 7.5)
    c.drawString(left, 12*mm, report_context["header"].get("footer", "Generated by NeurovaX Clinical Engine. Not a medical diagnosis. For clinician use."))

    c.save()
    buf.seek(0)
    return buf.read()
