from apps.clinical_ops.models import AssessmentOrder
from apps.clinical_ops.models_assessment import AssessmentResult
from apps.clinical_ops.models_report import AssessmentReport

def build_report_context(order: AssessmentOrder) -> dict:
    # Must exist
    result = AssessmentResult.objects.get(order=order)

    # Your scoring output MUST have this structure; if not, map it here.
    # Expected minimal:
    # result.result_json["summary"] = {"primary_severity": "...", "has_red_flags": bool, "red_flags": [..]}
    # result.result_json["tests"] = [{"name": "...", "score": "...", "band": "..."}]

    rj = result.result_json or {}
    summary = rj.get("summary", {}) or {}

    # 🔒 NORMALIZE FOR SIGNOFF COMPLIANCE
    if "has_red_flags" not in summary:
        summary["has_red_flags"] = False

    if "red_flags" not in summary:
        summary["red_flags"] = []

    result.result_json["summary"] = summary

    tests = []

    per_test = rj.get("per_test", {})
    for test_code, test_data in per_test.items():
        tests.append({
            "name": test_code,
            "score": test_data.get("score"),
            "band": test_data.get("severity"),
        })

    # signoff
    signoff_status = "PENDING"
    signed_by = "-"
    role = "-"
    signed_at = "-"
    method = "-"
    reason = "-"
    try:
        rep = AssessmentReport.objects.get(order=order)
        signoff_status = rep.signoff_status or "PENDING"
        signed_by = rep.signed_by_name or "-"
        role = rep.signed_by_role or "-"
        signed_at = rep.signed_at.isoformat() if rep.signed_at else "-"
        method = rep.signoff_method or "-"
        reason = rep.signoff_reason or "-"
    except AssessmentReport.DoesNotExist:
        pass

    ctx = {
        "header": {
            "org_name": "NeurovaX Diagnostics",
            "lab_line": "Clinical Assessment Unit",
            "footer": "Generated by NeurovaX Clinical Engine. For screening support only. Requires clinician review. For clinician use."
        },
        "patient": {
            "full_name": order.patient.full_name,
            "age": order.patient.age,
            "sex": order.patient.sex,
            "mrn": getattr(order.patient, "mrn", None),
            "phone": getattr(order.patient, "phone", None),
        },
        "order": {
            "id": order.id,
            "battery_code": order.battery_code,
            "battery_version": order.battery_version,
            "administration_mode": order.administration_mode,
            "encounter_type": order.encounter_type,
            "created_at": order.created_at.isoformat(),
            "completed_at": order.completed_at.isoformat() if order.completed_at else None,
        },
        "summary": {
            "primary_severity": summary.get("primary_severity"),
            "has_red_flags": bool(summary.get("has_red_flags", False)),
        },
        "red_flags": summary.get("red_flags", []) or [],
        "tests": tests or [],
        "disclaimers": [
            "This report is generated from standardized self-report instruments.",
            "It does NOT provide standalone clinical decisions.",
            "Final clinical decisions must be made by a registered medical practitioner.",
            "If self-harm thoughts are reported, immediate clinical assessment is required."
        ],
        "signoff": {
            "status": signoff_status,
            "signed_by": signed_by,
            "role": role,
            "signed_at": signed_at,
            "method": method,
            "reason": reason,
        }
    }
    # attach response quality flags if present
    try:
        q = order.response_quality
        ctx["summary"]["response_quality"] = {
            "duration_seconds": q.duration_seconds,
            "too_fast_flag": q.too_fast_flag,
            "straight_lining_flag": q.straight_lining_flag,
            "inconsistency_flag": q.inconsistency_flag,
        }
    except Exception:
        ctx["summary"]["response_quality"] = None

    return ctx
