# Generated by Django 5.2.4 on 2026-01-10 09:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('patient_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('encounter_type', models.CharField(max_length=20)),
                ('administration_mode', models.CharField(max_length=20)),
                ('battery_code', models.CharField(max_length=50)),
                ('battery_version', models.CharField(default='1.0', max_length=10)),
                ('status', models.CharField(default='CREATED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatterySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(default='NOT_STARTED', max_length=30)),
                ('current_test_index', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='clinical.clinicalorder')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('report_json', models.JSONField()),
                ('status', models.CharField(default='GENERATED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='clinical.clinicalorder')),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('test_code', models.CharField(max_length=30)),
                ('test_version', models.CharField(default='1.0', max_length=10)),
                ('test_order_index', models.IntegerField()),
                ('raw_responses', models.JSONField(default=list)),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('time_submitted', models.DateTimeField(blank=True, null=True)),
                ('computed_score', models.IntegerField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=50, null=True)),
                ('score_range', models.CharField(blank=True, max_length=20, null=True)),
                ('reference', models.CharField(blank=True, max_length=20, null=True)),
                ('red_flags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='clinical.batterysession')),
            ],
        ),
    ]
