# Generated by Django 5.2.4 on 2026-01-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClinicalReport',
        ),
    ]
