# Generated by Django 5.2.4 on 2026-01-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_delete_clinicalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalorder',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
