# Generated by Django 5.2.4 on 2026-01-24 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_clinicalorder_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='clinical.batterysession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'key'), name='unique_idem_key_per_session')],
            },
        ),
    ]
