# Generated by Django 5.2.4 on 2026-01-14 05:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(blank=True, max_length=64, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(max_length=16)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clinical_ops.org')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_code', models.CharField(max_length=64)),
                ('battery_version', models.CharField(default='1.0', max_length=16)),
                ('encounter_type', models.CharField(default='OPD', max_length=16)),
                ('referring_unit', models.CharField(blank=True, max_length=128, null=True)),
                ('administration_mode', models.CharField(choices=[('KIOSK', 'In-clinic kiosk/tablet'), ('QR_PHONE', 'Patient phone via QR/link'), ('ASSISTED', 'Assisted by staff')], default='KIOSK', max_length=16)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('AWAITING_REVIEW', 'Awaiting Review'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('verified_by_staff', models.BooleanField(default=False)),
                ('public_token', models.CharField(max_length=64, unique=True)),
                ('public_link_expires_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clinical_ops.org')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clinical_ops.patient')),
            ],
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['org', 'mrn'], name='clinical_op_org_id_82e17c_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['org', 'full_name'], name='clinical_op_org_id_826bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentorder',
            index=models.Index(fields=['org', 'status', 'created_at'], name='clinical_op_org_id_bf6246_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentorder',
            index=models.Index(fields=['org', 'battery_code'], name='clinical_op_org_id_9cf41a_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentorder',
            index=models.Index(fields=['public_token'], name='clinical_op_public__aafee2_idx'),
        ),
    ]
