# Generated by Django 5.2.4 on 2026-01-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentorder',
            name='delivery_mode',
            field=models.CharField(choices=[('HOSPITAL_ONLY', 'Hospital record only'), ('ALLOW_PATIENT_DOWNLOAD', 'Allow patient download'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PRINT', 'Print')], default='HOSPITAL_ONLY', max_length=64),
        ),
        migrations.AddField(
            model_name='assessmentorder',
            name='delivery_target',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
