# Generated by Django 5.2.4 on 2026-01-14 05:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ops', '0002_assessmentorder_delivery_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.IntegerField(default=0)),
                ('straight_lining_flag', models.BooleanField(default=False)),
                ('too_fast_flag', models.BooleanField(default=False)),
                ('inconsistency_flag', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response_quality', to='clinical_ops.assessmentorder')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_ops.org')),
            ],
        ),
    ]
