# Generated by Django 5.2.4 on 2026-01-14 07:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ops', '0003_responsequality'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_json', models.JSONField(default=dict)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='clinical_ops.assessmentorder')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_ops.org')),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'submitted_at'], name='clinical_op_org_id_dbc25a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_json', models.JSONField(default=dict)),
                ('primary_severity', models.CharField(blank=True, max_length=64, null=True)),
                ('has_red_flags', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='clinical_ops.assessmentorder')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_ops.org')),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'computed_at'], name='clinical_op_org_id_3caf9d_idx'), models.Index(fields=['org', 'has_red_flags'], name='clinical_op_org_id_fca8e9_idx')],
            },
        ),
    ]
