# Generated by Django 5.2.4 on 2026-01-14 09:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ops', '0004_assessmentresponse_assessmentresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='clinical_reports/%Y/%m/%d/')),
                ('signoff_status', models.CharField(default='PENDING', max_length=32)),
                ('signed_by_name', models.CharField(blank=True, max_length=128, null=True)),
                ('signed_by_role', models.CharField(blank=True, max_length=64, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generated_by_user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='clinical_ops.assessmentorder')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_ops.org')),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'generated_at'], name='clinical_op_org_id_a4415c_idx'), models.Index(fields=['org', 'signoff_status'], name='clinical_op_org_id_91f37a_idx')],
            },
        ),
    ]
