# Generated by Django 5.2.4 on 2026-01-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ops', '0005_assessmentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentreport',
            name='signoff_method',
            field=models.CharField(default='SYSTEM', max_length=32),
        ),
        migrations.AddField(
            model_name='assessmentreport',
            name='signoff_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
