# Generated by Django 5.2.4 on 2026-01-14 12:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ops', '0006_assessmentreport_signoff_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('actor_user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('actor_name', models.CharField(blank=True, max_length=128, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=64, null=True)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_ops.org')),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'event_type', 'created_at'], name='clinical_op_org_id_6ed679_idx'), models.Index(fields=['org', 'entity_type', 'entity_id'], name='clinical_op_org_id_e602bf_idx')],
            },
        ),
    ]
