# Generated by Django 5.2.4 on 2026-01-15 07:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ops', '0007_auditevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_version', models.CharField(default='V1', max_length=32)),
                ('consent_language', models.CharField(default='en', max_length=16)),
                ('consent_given_by', models.CharField(default='SELF', max_length=32)),
                ('guardian_name', models.CharField(blank=True, max_length=128, null=True)),
                ('allow_data_processing', models.BooleanField(default=True)),
                ('allow_report_generation', models.BooleanField(default=True)),
                ('allow_share_with_clinician', models.BooleanField(default=True)),
                ('allow_patient_copy', models.BooleanField(default=False)),
                ('consent_text_snapshot', models.TextField()),
                ('consented_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='clinical_ops.assessmentorder')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_ops.org')),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'consent_version', 'consented_at'], name='clinical_op_org_id_d17725_idx')],
            },
        ),
    ]
