# Generated by Django 5.2.4 on 2026-01-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ops', '0008_consentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentorder',
            name='report_access_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='assessmentorder',
            name='report_access_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
