# Generated by Django 5.2.4 on 2026-01-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ops', '0009_assessmentorder_report_access_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentorder',
            name='data_retention_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentorder',
            name='deletion_status',
            field=models.CharField(default='ACTIVE', max_length=32),
        ),
    ]
