# Generated by Django 5.2.4 on 2026-01-15 13:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ops', '0010_assessmentorder_data_retention_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='REQUESTED', max_length=32)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_ops.assessmentorder')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_ops.org')),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'status', 'requested_at'], name='clinical_op_org_id_365e12_idx')],
            },
        ),
    ]
