# Generated by Django 5.2.4 on 2026-02-09 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ops', '0012_alter_assessmentorder_org_alter_assessmentreport_org_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('questions_json', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=16)),
                ('screening_label', models.CharField(max_length=255)),
                ('signoff_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_batteries', to='clinical_ops.assessment')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_tests', to='clinical_ops.battery')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('battery', 'assessment')},
            },
        ),
    ]
