# Generated by Django 5.2.4 on 2026-02-12 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ops', '0013_assessment_battery_batteryassessment'),
        ('core', '0003_organization_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='request_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='severity',
            field=models.CharField(default='INFO', max_length=20),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='entity_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='entity_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['event_type', 'created_at'], name='clinical_op_event_t_e76d69_idx'),
        ),
    ]
