# Generated by Django 5.2.4 on 2026-02-12 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ops', '0015_publicaccesstoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicaccesstoken',
            old_name='ip_address',
            new_name='bound_ip',
        ),
        migrations.RenameField(
            model_name='publicaccesstoken',
            old_name='used_at',
            new_name='last_used_at',
        ),
        migrations.RemoveField(
            model_name='publicaccesstoken',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='publicaccesstoken',
            name='bound_user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publicaccesstoken',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publicaccesstoken',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secure_token', to='clinical_ops.assessmentorder'),
        ),
    ]
