# Generated by Django 5.2.4 on 2026-02-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ops', '0016_rename_ip_address_publicaccesstoken_bound_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentorder',
            name='public_token',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
