# Generated by Django 5.2.4 on 2026-02-13 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ops', '0017_alter_assessmentorder_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaccesstoken',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_tokens', to='clinical_ops.assessmentorder'),
        ),
    ]
