# Generated by Django 5.2.4 on 2026-02-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ops', '0018_alter_publicaccesstoken_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentorder',
            name='report_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentorder',
            name='report_failed_attempts_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
