# Generated by Django 5.2.11 on 2026-02-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ops', '0020_add_regulatory_app_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentorder',
            name='patient_acceptance_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentorder',
            name='patient_acceptance_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16),
        ),
        migrations.AddField(
            model_name='assessmentorder',
            name='patient_acceptance_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
