# Generated by Django 5.2.11 on 2026-02-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ops', '0021_assessmentorder_patient_acceptance_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentorder',
            name='patient_acceptance_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
