# Generated by Django 5.2.4 on 2025-12-31 15:06

import common.immutability
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_sessions', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedFlagEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('AMBER', 'AMBER'), ('RED', 'RED'), ('CRITICAL', 'CRITICAL')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_sessions.session')),
            ],
            bases=(common.immutability.ImmutableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FlagAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_by_user_id', models.IntegerField()),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safety.redflagevent')),
            ],
            bases=(common.immutability.ImmutableModelMixin, models.Model),
        ),
    ]
