# Generated by Django 5.2.4 on 2026-01-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_sessions', '0004_consentrecord_clinical_se_organiz_411bc4_idx_and_more'),
        ('core', '0001_initial'),
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flagacknowledgement',
            index=models.Index(fields=['organization', 'flag'], name='safety_flag_organiz_050255_idx'),
        ),
        migrations.AddIndex(
            model_name='flagacknowledgement',
            index=models.Index(fields=['organization', 'acknowledged_at'], name='safety_flag_organiz_487329_idx'),
        ),
        migrations.AddIndex(
            model_name='redflagevent',
            index=models.Index(fields=['organization', 'session'], name='safety_redf_organiz_cee7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='redflagevent',
            index=models.Index(fields=['organization', 'level'], name='safety_redf_organiz_af676e_idx'),
        ),
        migrations.AddIndex(
            model_name='redflagevent',
            index=models.Index(fields=['organization', 'created_at'], name='safety_redf_organiz_ab8f90_idx'),
        ),
    ]
