# Generated by Django 5.2.4 on 2026-01-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['organization', 'created_at'], name='patients_pa_organiz_f38037_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['organization', 'name'], name='patients_pa_organiz_c45398_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['organization', 'phone'], name='patients_pa_organiz_62612b_idx'),
        ),
    ]
