# Generated by Django 5.2.4 on 2025-12-31 15:06

import common.immutability
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clinical_sessions', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('severity_band', models.CharField(max_length=50)),
                ('subscales', models.JSONField(default=dict)),
                ('engine_version', models.CharField(max_length=20)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_sessions.session')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.testdefinition')),
            ],
            options={
                'unique_together': {('organization', 'session', 'test')},
            },
            bases=(common.immutability.ImmutableModelMixin, models.Model),
        ),
    ]
