# Generated by Django 5.2.4 on 2026-01-02 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_sessions', '0003_sessionconsent'),
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('severity', models.CharField(max_length=32)),
                ('breakdown', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinical_sessions.session')),
            ],
        ),
        migrations.DeleteModel(
            name='ScoreResult',
        ),
    ]
