# Generated by Django 5.2.4 on 2026-01-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_sessions', '0004_consentrecord_clinical_se_organiz_411bc4_idx_and_more'),
        ('scoring', '0002_score_delete_scoreresult'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['session'], name='scoring_sco_session_c75173_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['created_at'], name='scoring_sco_created_22ae19_idx'),
        ),
    ]
