# Generated by Django 5.2.4 on 2026-01-12 09:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0002_delete_clinicalreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalSignoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('clinician_name', models.CharField(blank=True, max_length=200)),
                ('clinician_role', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_signoff', to='clinical.clinicalorder')),
            ],
        ),
    ]
